### ISSUE TITLE
Addition of Images to Transcripts

### ISSUE THREAD

**Issue by freddiekrugerrand** [bitcointranscripts/bitcointranscripts#106]
I have started working on a transcript for Bastien Teinturier's [Lightning Privacy](https://bitcointv.com/w/2pXyaypeMThT5tM3MUWcgN) talk at Adopting Bitcoin. 

Towards the end of the talk, he speaks about Trampoline Routing with heavy reference to his slides (eg: Alice routes to Bob, Bob sends to Carol etc). It is quite difficult to understand from just reading the transcript. 

If the slides are available, is it possible to add images to transcripts to make them easier to follow? I would think that this is the case for a lot of Lightning transcripts.

**Comment by freddiekrugerrand** [comment]
Thank you @michaelfolkson, if I can get the slides (I have requested from Bastien) then I will put the PR up with a link in the meantime. 

> I think my preference would be to add a subdirectory to the directory in which you are placing the transcript called say images and putting the file there

This sounds like a good idea to me, perhaps with some naming standard like there is for transcripts? Something like: `date-transcriptname-imagename`.

Images seem like they need a high-level decision from the maintainers of the repo. so I will await a decision there.

**Comment by adamjonas** [comment]
I don't have a strong opinion as long as it makes sense. I would personally use a link rather than keeping them in the repo but a subdir in the topic dir seems like a totally reasonable route as well.

Once you add this, could you please update the README with instructions for future contributors?

Thanks!

**Comment by kouloumos** [comment]
I'll close this issue as I've just opened https://github.com/bitcointranscripts/bitcointranscripts/issues/326 for further discussing the addition of supportive material for transcripts.
