### ISSUE TITLE
Metadata Additions 

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/bitcointranscripts#202]
### Overview 

This issue is for the coordination of the metadata additions effort as outlined in https://github.com/bitcointranscripts/bitcointranscripts/issues/171#issuecomment-1242058905

> 1. Extract metadata for all transcripts to utilize [add speakers taxonomy and date support bitcointranscripts.github.io#42](https://github.com/bitcointranscripts/bitcointranscripts.github.io/pull/42) together with minor UI changes as mentioned [here](https://github.com/bitcointranscripts/bitcointranscripts/pull/180#discussion_r929028332) to utilize new metadata and improve discoverability [WIP].

and after the recent interest of @tvpeter to help on this (https://github.com/bitcointranscripts/bitcointranscripts/pull/201). 

Because of the new UI changes that are not yet part of the website, there is a need for those metadata changes to first be merged in another branch, different than master. I created the [metadata-addition branch](https://github.com/bitcointranscripts/bitcointranscripts/tree/metadata-additions) based on the most recent master. The plan is for all the changes related to this effort to be first merged there and merge that branch with master as soon as the new UI (better display of title, speakers, date, tags) is ready. 

~The plan is to have one commit per transcript category (e.g. austin-bitcoin-developers, advancing-bitcoin) to step-by-step touch all transcripts while simplifying reviewing and merging.~

~Anybody interested on helping with this effort can indicate interest here, just to avoid duplicate work.~
Edit: Metadata changes are now on the [metadata-addition branch](https://github.com/bitcointranscripts/bitcointranscripts/tree/metadata-additions), I'll close this as soon as the changes are on master.

**Comment by adamjonas** [comment]
We are using this data for an unrelated project that indexes these files for search. A dependency on the display of the the content defeats the whole purpose of having them in two repos. I think it makes sense to merge into master given the amount of work and review that's already been invested.

**Comment by adamjonas** [comment]
@kouloumos didn't see a response from you so went ahead and opened https://github.com/bitcointranscripts/bitcointranscripts/pull/214. I'd like to get this in unless there are any objections. This is a big enough change as is, I think will can follow-up with additional requirements for the UI when it is ready.

**Comment by kouloumos** [comment]
> @kouloumos didn't see a response from you so went ahead and opened #214. I'd like to get this in unless there are any objections. This is a big enough change as is, I think will can follow-up with additional requirements for the UI when it is ready.

Sounds good, apologies for the delay, I kind of messed up my notifications.
