### ISSUE TITLE
Provision to add images directly in the repo

### ISSUE THREAD

**Issue by delcin-raj** [bitcointranscripts/bitcointranscripts#324]
With the current design in order to add images to the transcripts, it has to be hosted with some third party hosting providers and include that link.
Is this the preferred way or can the images be hosted within this repository itself?

**Comment by kouloumos** [comment]
What kind of image are you looking to add? What's its connection with the transcript?

**Comment by delcin-raj** [comment]
I'm currently working on CoinJoin done right-> https://www.youtube.com/watch?v=khmLiM9xhwk.
In this talk images of transaction graphs, mathematical equations etc., where used extensively.
They were frequently referred using physical markers by the speaker as well.
So those references where not picked up by the transcripts.
By adding the image I could easily refer them by labels.

I believe in general this feature will be useful.

**Comment by kouloumos** [comment]
I do not have a strong opinion about the usage of images, but it's true that with the current flow (through the in-app Editor) you cannot add images as part of the repo. Not sure if external hosting is the best idea as it's less future-proof. The same issue was raised in https://github.com/bitcointranscripts/bitcointranscripts/issues/106 btw. We'll need to think about it - maybe you can start with external hosting as it's easier for now.

What if the reader had access to the slides? Would that be helpful? I do not see a link on the video, but maybe, if we ask nicely, @AdamISZ can give us access to the presentation.

**Comment by AdamISZ** [comment]
Hi @kouloumos . Yes it's a bit frustrating how often the slides of talks aren't easily available to people after the event.

Maybe I can attach it here? Let's try ... 
[cdmx2022.pdf](https://github.com/bitcointranscripts/bitcointranscripts/files/13460446/cdmx2022.pdf)

**Comment by delcin-raj** [comment]
Thanks @AdamISZ .
This would make the transcript more readable.

**Comment by AdamISZ** [comment]
> Thanks @AdamISZ . This would make the transcript more readable.

Thanks for working on it!

**Comment by kouloumos** [comment]
> Hi @kouloumos . Yes it's a bit frustrating how often the slides of talks aren't easily available to people after the event.
> 
> Maybe I can attach it here? Let's try ... [cdmx2022.pdf](https://github.com/bitcointranscripts/bitcointranscripts/files/13460446/cdmx2022.pdf)

Thank you @AdamISZ!

@delcin-raj the Editor does not support attaching slides to the transcripts (yet?). Usually the slides are hosted somewhere else and we just post a link, but we should probably start thinking about future-proofing that, cause slides are important for context. That said, having slides in this repo doesn't make sense cause it's gonna grow in size very quickly - same goes for pictures. As we don't have a solution yet, you could host the slides somewhere and add a link at the beginning of the transcript. 

I'll close this issue as I've just opened https://github.com/bitcointranscripts/bitcointranscripts/issues/326 for further discussing the addition of supportive material for transcripts.
