### ISSUE TITLE
Can't Submit Transcription.

### ISSUE THREAD

**Issue by masud-abdulkadir** [bitcointranscripts/bitcointranscripts#351]
Hello, I was editing the 'SNICKER' transcription and wanted to submit my changes, but it doesn't seem to be working. Screnshot Below:

![SNICKER](https://github.com/bitcointranscripts/bitcointranscripts/assets/74487067/7fa2b1cb-7c72-48eb-bca5-e149c657546a)

The sreenshot of the error that shows up when submitting the transcript:
![submit_bug](https://github.com/bitcointranscripts/bitcointranscripts/assets/74487067/1f31ac47-add4-40d6-8575-f01674f9f7af)

Let me know if you'd like the edited transcript submitted, using a different method to submit it.

**Comment by masud-abdulkadir** [comment]
Just a heads up, the transcript is now considered 'EXPIRED' 
<img width="955" alt="image" src="https://github.com/bitcointranscripts/bitcointranscripts/assets/74487067/a0380f22-8090-4398-8001-e17cb17f78c5">

**Comment by masud-abdulkadir** [comment]
Since it's expired, I can't submit it anymore. Let me know if I can do anything help :) thanks.

**Comment by delcin-raj** [comment]
I'm too facing this issue now.
Unable to make the first commit.

**Comment by kouloumos** [comment]
Sorry for the late response. We're doing a major refactor which we beleive may fix this issue. Please hang in there for a bit. We'll let you know when its deployed.

Sorry for the inconvenience and thanks for your patience.

**Comment by kouloumos** [comment]
We have successfully fixed the issue as part of our recent updates.

You should now be able to submit transcripts without any further inconvenience. We appreciate your patience and understanding while we addressed this matter.

We would be delighted to see you back on the platform. If you encounter any further issues or have any feedback, please don't hesitate to reach out to us. Your input is invaluable in helping us improve the platform. If you haven't already, I encourage you to join our [Discord server](https://discord.gg/76wCxgeyvM). It's a great place to connect with fellow contributors, ask questions, share insights, and stay updated on new transcripts available for review.

Thank you once again for your understanding and support.
