### ISSUE TITLE
Transcript editor should save the work automatically.

### ISSUE THREAD

**Issue by edilmedeiros** [bitcointranscripts/bitcointranscripts#376]
Or, at least, the save button should be more evident in the UI with a recommendation in the tutorial.

I lost about an hour's worth of work because of a crash in my browser, just to realize the system does not auto-save. 
That was when I found the save button next to the submit button; they were both hidden at the bottom of the page.

**Comment by kouloumos** [comment]
> Or, at least, the save button should be more evident in the UI with a recommendation in the tutorial.
> 
> I lost about an hour's worth of work because of a crash in my browser, just to realize the system does not auto-save. That was when I found the save button next to the submit button; they were both hidden at the bottom of the page.

Thank you very much for taking the time to share your thoughts with us @edilmedeiros! Your feedback is super important, and we're going to prioritize this. Your input helps us improve, and we appreciate your patience as we enhance the project. If you have more suggestions or run into issues, feel free to give us a shout. Thanks for being a part of our community.

**Comment by kouloumos** [comment]
Closed with https://github.com/bitcointranscripts/transcription-review-front-end/issues/254

Implementing auto-save functionality is non-trivial and, unfortunately, will not be addressed at this time. To provide additional context, each reviewer's save action corresponds to a commit on the review branch. Therefore, enabling auto-saving with every change is not feasible.

We are actively discussing potential solutions to incorporate auto-save as a future enhancement. This may involve temporarily storing work in browser storage or implementing auto-save commits on a predefined time interval.
