### ISSUE TITLE
Bitcoin Explained - some existing transcripts

### ISSUE THREAD

**Issue by Sjors** [bitcointranscripts/bitcointranscripts#388]
I had a few episodes transcribed by humans for my book:

https://github.com/Sjors/nado-book/tree/master/transcripts

You're welcome to copy these.

**Comment by edilmedeiros** [comment]
@kouloumos How do you feel about adding these? 
I can help by doing the first work of sanitizing them to be more close to the standards of this repo.

**Comment by kouloumos** [comment]
> @kouloumos How do you feel about adding these? I can help by doing the first work of sanitizing them to be more close to the standards of this repo.

Thank you for stepping up and offering to help with the transcripts @edilmedeiros!

They do indeed need some sanitation before being added to the repo. However, I already have a few Python scripts that can assist with breaking the text into the one-sentence-per-line format and adding an empty line after each speaker. So, no need to worry about that aspect.

While those transcripts may not have timestamps like the others, they're still valuable additions. If you could help by filtering them (ensuring we haven't already added some) and converting them into markdown files with all the necessary metadata, that would be incredibly helpful. Once you've opened a PR, I can easily apply the scripts and handle the formatting automatically.

Thank you once again for offering your assistance. Feel free to reach out if you have any questions or need further clarification.

**Comment by kouloumos** [comment]
All the transcripts have now been merged with the help of @edilmedeiros.
