### ISSUE TITLE
Turnaround from PR merge to getting transcripts of recent events up on the website

### ISSUE THREAD

**Issue by michaelfolkson** [bitcointranscripts/bitcointranscripts#42]
For transcripts of recent presentations/discussions I have on a couple of occasions continued to share links to Kanzure's site rather than btctranscripts.com because the transcripts are often uploaded to his site faster.

I can continue doing this or we could discuss how to reduce the time of getting transcripts (of recent events, historical events don't have the same timely considerations in my view) uploaded to the site.

There is a quality consideration for new contributors' PRs which impacts how speedily we can merge their PRs. But can we speed up the time from merge to getting the transcript up on the site?

**Comment by adamjonas** [comment]
Yeah, that's the process thing that has been bottlenecked by me. You do have admin rights to both repos so you could do it yourself. Creating a script that auto-updates the site repo is also possible.

**Comment by michaelfolkson** [comment]
Cool, thanks. I'm happy to do it. Can you provide instructions either here or privately?

**Comment by adamjonas** [comment]
Rough steps that I follow are:
```
git clone git@github.com:bitcointranscripts/bitcointranscripts.github.io.git
cd content
git pull origin master
cd ..
hugo
git add .
git commit -am 'update content <date>'
```
Push to your repo and open a PR.
