### ISSUE TITLE
Incorrect link to finished transcripts

### ISSUE THREAD

**Issue by varmur** [bitcointranscripts/bitcointranscripts#432]
In the "Past Jobs" section, the "Links" column has links to the PR and the finished transcripts.

The finished transcript links are incorrect, they do not have the correct directory structure.

For example,
The displayed link points to https://btctranscripts.com/misc/covenants-part-2.
The correct link is https://btctranscripts.com/bitcoin-design/learning-bitcoin-and-design/covenants-part-2/

**Comment by kouloumos** [comment]
@varmur thank you for bringing this to our attention! This is a front-end related issue, so  I've relocated it to a more relevant location that allows us to address it more efficiently: https://github.com/bitcointranscripts/transcription-review-front-end/issues/271
