### ISSUE TITLE
Refine Taxonomies and Metadata in Transcript Files

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/bitcointranscripts#518]
As part of the redesign of Bitcoin Transcripts, we are refining our taxonomies and information architecture. This refinement involves changes to how we organize metadata in individual transcript markdown files and source files.

### Current Structure
Previously, each transcript or resource file contained a `categories` field in its metadata. We are now moving the `categories` field from individual files to the Source level. A Source, such as [`chaincode-labs/chaincode-podcast`](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/chaincode-labs/chaincode-podcast) or [`bitcoin-explained`](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/bitcoin-explained), contains resources like podcast episodes, conference talks, or YouTube videos, and a transcript is generated from each resource.

The hierarchy is defined as follows:
```
├── README.md
└── /source-group
    ├── _index.md
    ├── /source1
        ├── _index.md
        ├── transcript-file.md
        ├── another-transcript-file.md
        └── ...
    ├── source2
        ├── _index.md
        ├── transcript-file.md
        └── ...
└── /single-source
    ├── _index.md
    ├── transcript-file.md
    └── ...
└── ...
```

### What Needs to Be Done
1. **Remove `categories` from Individual Transcripts**: The `categories` metadata should be removed from all individual transcript markdown files.
2. **Add Refined `types` Metadata at Source Level**: The `categories` field should be replaced by `types` and added to the `_index.md` file at the Source level (examples of Source level file: [1](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/advancing-bitcoin/_index.md), [2](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/bitcoin-explained/_index.md)). 
  Examples:
    - all transcripts under `chaincode-labs/chaincode-podcast` currently have `categories: ["podcast"]` ([example](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/chaincode-labs/chaincode-podcast/2020-01-28-pieter-wuille-part2.md)). This should be removed from each transcript and added to [`chaincode-labs/chaincode-podcast/_index.md`](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/chaincode-labs/chaincode-podcast/_index.md) as `types: ["podcast"]`.
    - all transcripts under `advancing-bitcoin/{2019,2020,2022,2023}` currently have `categories: ["conference"]`. This should be removed from each transcript and added to [`advancing-bitcoin/_index.md`](https://github.com/bitcointranscripts/bitcointranscripts/blob/master/advancing-bitcoin/_index.md) as `types: ["conference"]`.
3. **Flatten Directory Structure for Nested Sources**: Some sources are currently nested under the organization that generates them. We've decided to move these sources out of their nested folders for consistency. This applies to cases like:
   - `chaincode-labs/chaincode-podcast` should become `chaincode-podcast`
   - `chaincode-labs/chaincode-residency` should become `chaincode-residency`
   - `bitcoin-magazine/bitcoin-2024` should become `bitcoin-2024`

### Updated Types List
The current list of categories will be refined and reduced when transitioning to types. The [existing categories can be found here](https://btctranscripts.com/categories/).

They will be refined to a new set of types:
- podcast
- meetup
- call
- workshop
- conference
- various

We are still considering the final list of types, and suggestions are welcome.

### Directory Structure Changes

The new directory structure should look like this:

```
├── README.md
└── /chaincode-podcast
    ├── _index.md
    ├── transcript-file.md
    ├── another-transcript-file.md
    └── ...
└── /chaincode-residency
    ├── _index.md
    ├── transcript-file.md
    └── ...
└── /bitcoin-2024
    ├── _index.md
    ├── transcript-file.md
    └── ...
└── ...

**Comment by kouloumos** [comment]
In hindsight, this wasn't a "good first issue".  I'm glad nobody picked it! :sweat_smile:

**Comment by kouloumos** [comment]
@aassoiants  Our current categorization includes both "workshop" and "conference" `types`. However, our "workshop" entries:
- [W3 Blockchain Workshop](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/w3-blockchain-workshop-2016)
- [Decentralized Financial Architecture Workshop](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/decentralized-financial-architecture-workshop)
- [Coordination of Decentralized Finance Workshop](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/coordination-of-decentralized-finance-workshop)

seem more conference-like in scope and scale.

I think that we should Reclassify these "workshops" under the "conferences" type to

- Improve consistency in our categorization
- More accurately reflect the nature and scope of these events
- Simplify our taxonomy for easier navigation and search

Current stats:
- 39 transcripts with `category == workshop`
- 542 transcripts with `category == conference`

**Comment by kouloumos** [comment]
We need to address the categorization of [Bitcoin Core Dev Tech](https://github.com/bitcointranscripts/bitcointranscripts/tree/master/bitcoin-core-dev-tech) events. Currently, these are under the `core-dev-tech` category, which we've removed as it was only applicable to this specific source.

My proposal is to reclassify these under `workshop`.

Bitcoin Core Dev Tech events are [a "hackathon"](https://coredev.tech/faq.html) focused on collaborative coding and project acceleration rather than a conference. This aligns more closely with the interactive, hands-on nature of workshops rather than the presentation-focused structure of conferences. While I've [previously suggested merging workshop and conference types](https://github.com/bitcointranscripts/bitcointranscripts/issues/518#issuecomment-2404903001), `workshop` currently best represents these events' format and purpose.

@aassoiants, any thoughts ?

**Comment by aassoiants** [comment]
> I think that we should Reclassify these "workshops" under the "conferences" type to
I trust your judgment on reclassifying things.

> My proposal is to reclassify these under workshop.
lgmt

> 39 transcripts with category == workshop
> 542 transcripts with category == conference
There's few transcripts categorized as workshops - i wonder if it's a helpful category in the first place?
