### ISSUE TITLE
clean up/add andrew poelsta/jeremy rubin covenants panel

### ISSUE THREAD

**Issue by JeremyRubin** [bitcointranscripts/bitcointranscripts#83]
https://gist.github.com/JeremyRubin/2d69841755cf048f0c45bef8edf63b4c

see notes here, audio recording available but not publicly.

**Comment by michaelfolkson** [comment]
Happy to clean this one up and add to the repo @JeremyRubin. Can you share the audio recording privately? That would help with the clean up.
